// domain
import type { CharacterNames } from "#/constants/CharacterNames";

const eras = [
	"Legacy Era",
	"Era of Deadly Pursuits",
	"Era of Apprentices",
	"Era of the Cavalry",
	"Era of Revenge of the Sith",
	"Era of Piracy",
	"Era of Anniversary",
	"Era of Andor",
	"Era of New Republic",
];

type Era = (typeof eras)[number];

const eraByCharacter: Map<CharacterNames, Era> = new Map([
	["4LOM", "Era of Deadly Pursuits"],
	["50RT", "Legacy Era"],
	["AAYLASECURA", "Legacy Era"],
	["ADMINISTRATORLANDO", "Legacy Era"],
	["ADMIRALACKBAR", "Legacy Era"],
	["ADMIRALPIETT", "Legacy Era"],
	["ADMIRALRADDUS", "Legacy Era"],
	["AHSOKATANO", "Legacy Era"],
	["AMILYNHOLDO", "Legacy Era"],
	["ANAKINKNIGHT", "Legacy Era"],
	["APPO", "Era of Revenge of the Sith"],
	["ARCTROOPER501ST", "Legacy Era"],
	["ARMORER", "Legacy Era"],
	["ASAJJDARKDISCIPLE", "Era of Anniversary"],
	["ASAJVENTRESS", "Legacy Era"],
	["AURRA_SING", "Legacy Era"],
	["BADBATCHECHO", "Legacy Era"],
	["BADBATCHHUNTER", "Legacy Era"],
	["BADBATCHOMEGA", "Legacy Era"],
	["BADBATCHTECH", "Legacy Era"],
	["BADBATCHWRECKER", "Legacy Era"],
	["B1BATTLEDROIDV2", "Legacy Era"],
	["B2SUPERBATTLEDROID", "Legacy Era"],
	["BARRISSOFFEE", "Legacy Era"],
	["BASTILASHAN", "Legacy Era"],
	["BASTILASHANDARK", "Legacy Era"],
	["BATCHERS3", "Era of the Cavalry"],
	["BAYLANSKOLL", "Legacy Era"],
	["BAZEMALBUS", "Legacy Era"],
	["BB8", "Legacy Era"],
	["BENSOLO", "Legacy Era"],
	["BIGGSDARKLIGHTER", "Legacy Era"],
	["BISTAN", "Legacy Era"],
	["BOBAFETT", "Legacy Era"],
	["BOBAFETTSCION", "Legacy Era"],
	["BODHIROOK", "Legacy Era"],
	["BOKATAN", "Legacy Era"],
	["BOOMADIER", "Legacy Era"],
	["BOSSK", "Legacy Era"],
	["BOSSNASS", "Legacy Era"],
	["BOUSHH", "Legacy Era"],
	["BRUTUS", "Era of Piracy"],
	["BT1", "Legacy Era"],
	["C3POCHEWBACCA", "Legacy Era"],
	["C3POLEGENDARY", "Legacy Era"],
	["CADBANE", "Legacy Era"],
	["CALKESTIS", "Legacy Era"],
	["CANDEROUSORDO", "Legacy Era"],
	["CAPTAINDROGAN", "Legacy Era"],
	["CAPTAINENOCH", "Legacy Era"],
	["CAPTAINREX", "Legacy Era"],
	["CAPTAINSILVO", "Era of Piracy"],
	["CAPTAINTARPALS", "Legacy Era"],
	["CARADUNE", "Legacy Era"],
	["CARTHONASI", "Legacy Era"],
	["CASSIANANDOR", "Legacy Era"],
	["CASSIANUNDERCOVER", "Era of Andor"],
	["CC2224", "Legacy Era"],
	["CEREJUNDA", "Legacy Era"],
	["CHEWBACCALEGENDARY", "Legacy Era"],
	["CHIEFCHIRPA", "Legacy Era"],
	["CHIEFNEBIT", "Legacy Era"],
	["CHIRRUTIMWE", "Legacy Era"],
	["CHOPPERS3", "Legacy Era"],
	["CINTA", "Era of Andor"],
	["CLONESERGEANTPHASEI", "Legacy Era"],
	["CLONEWARSCHEWBACCA", "Legacy Era"],
	["COLONELSTARCK", "Legacy Era"],
	["COMMANDERAHSOKA", "Legacy Era"],
	["COMMANDERLUKESKYWALKER", "Legacy Era"],
	["CORUSCANTUNDERWORLDPOLICE", "Legacy Era"],
	["COUNTDOOKU", "Legacy Era"],
	["CROSSHAIRS3", "Era of the Cavalry"],
	["CT5555", "Legacy Era"],
	["CT7567", "Legacy Era"],
	["CT210408", "Legacy Era"],
	["DAKA", "Legacy Era"],
	["DARKREY", "Era of Apprentices"],
	["DARKTROOPER", "Legacy Era"],
	["DARTHBANE", "Legacy Era"],
	["DARTHMALAK", "Legacy Era"],
	["DARTHMALGUS", "Legacy Era"],
	["DARTHNIHILUS", "Legacy Era"],
	["DARTHREVAN", "Legacy Era"],
	["DARTHSIDIOUS", "Legacy Era"],
	["DARTHSION", "Legacy Era"],
	["DARTHTALON", "Legacy Era"],
	["DARTHTRAYA", "Legacy Era"],
	["DASHRENDAR", "Legacy Era"],
	["DATHCHA", "Legacy Era"],
	["DEATHTROOPER", "Legacy Era"],
	["DEATHTROOPERPERIDEA", "Legacy Era"],
	["DEDRAMEERO", "Era of Andor"],
	["DENGAR", "Legacy Era"],
	["DEPABILLABA", "Era of Revenge of the Sith"],
	["DIRECTORKRENNIC", "Legacy Era"],
	["DISGUISEDCLONETROOPER", "Era of Revenge of the Sith"],
	["DOCTORAPHRA", "Legacy Era"],
	["DROIDEKA", "Legacy Era"],
	["EETHKOTH", "Legacy Era"],
	["EIGHTHBROTHER", "Legacy Era"],
	["EMBO", "Legacy Era"],
	["EMPERORPALPATINE", "Legacy Era"],
	["ENFYSNEST", "Legacy Era"],
	["EPIXFINN", "Legacy Era"],
	["EPIXPOE", "Legacy Era"],
	["EWOKELDER", "Legacy Era"],
	["EWOKSCOUT", "Legacy Era"],
	["EZRABRIDGERS3", "Legacy Era"],
	["EZRAEXILE", "Legacy Era"],
	["FENNECSHAND", "Legacy Era"],
	["FIFTHBROTHER", "Legacy Era"],
	["FINN", "Legacy Era"],
	["FIRSTORDEREXECUTIONER", "Legacy Era"],
	["FIRSTORDEROFFICERMALE", "Legacy Era"],
	["FIRSTORDERSPECIALFORCESPILOT", "Legacy Era"],
	["FIRSTORDERTIEPILOT", "Legacy Era"],
	["FIRSTORDERTROOPER", "Legacy Era"],
	["FOSITHTROOPER", "Legacy Era"],
	["FULCRUMAHSOKA", "Legacy Era"],
	["GAMORREANGUARD", "Legacy Era"],
	["GARSAXON", "Legacy Era"],
	["GENERALHUX", "Legacy Era"],
	["GENERALKENOBI", "Legacy Era"],
	["GENERALSKYWALKER", "Legacy Era"],
	["GENERALSYNDULLA", "Era of Apprentices"],
	["GEONOSIANBROODALPHA", "Legacy Era"],
	["GEONOSIANSOLDIER", "Legacy Era"],
	["GEONOSIANSPY", "Legacy Era"],
	["GLAHSOKATANO", "Era of Apprentices"],
	["GLHONDO", "Era of Piracy"],
	["GLLEIA", "Legacy Era"],
	["GLREY", "Legacy Era"],
	["GRANDADMIRALTHRAWN", "Legacy Era"],
	["GRANDINQUISITOR", "Legacy Era"],
	["GRANDMASTERLUKE", "Legacy Era"],
	["GRANDMASTERYODA", "Legacy Era"],
	["GRANDMOFFTARKIN", "Legacy Era"],
	["GREATMOTHERS", "Legacy Era"],
	["GREEDO", "Legacy Era"],
	["GREEFKARGA", "Legacy Era"],
	["GRIEVOUS", "Legacy Era"],
	["GUNGANPHALANX", "Legacy Era"],
	["HANSOLO", "Legacy Era"],
	["HERASYNDULLAS3", "Legacy Era"],
	["HERMITYODA", "Legacy Era"],
	["HK47", "Legacy Era"],
	["HONDO", "Legacy Era"],
	["HOTHHAN", "Legacy Era"],
	["HOTHLEIA", "Legacy Era"],
	["HOTHREBELSCOUT", "Legacy Era"],
	["HOTHREBELSOLDIER", "Legacy Era"],
	["HUMANTHUG", "Legacy Era"],
	["HUNTERS3", "Era of the Cavalry"],
	["HUYANG", "Era of Apprentices"],
	["IDENVERSIOEMPIRE", "Legacy Era"],
	["IG11", "Legacy Era"],
	["IG12", "Legacy Era"],
	["IG86SENTINELDROID", "Legacy Era"],
	["IG88", "Legacy Era"],
	["IG90", "Era of Anniversary"],
	["IMAGUNDI", "Legacy Era"],
	["IMPERIALPROBEDROID", "Legacy Era"],
	["IMPERIALSUPERCOMMANDO", "Legacy Era"],
	["INQUISITORBARRISS", "Era of Anniversary"],
	["ITHANO", "Era of Piracy"],
	["JABBATHEHUTT", "Legacy Era"],
	["JANGOFETT", "Legacy Era"],
	["JARJARBINKS", "Legacy Era"],
	["JAWA", "Legacy Era"],
	["JAWAENGINEER", "Legacy Era"],
	["JAWASCAVENGER", "Legacy Era"],
	["JEDIKNIGHTCAL", "Legacy Era"],
	["JEDIKNIGHTCONSULAR", "Legacy Era"],
	["JEDIKNIGHTGUARDIAN", "Legacy Era"],
	["JEDIKNIGHTLUKE", "Legacy Era"],
	["JEDIKNIGHTREVAN", "Legacy Era"],
	["JEDIMASTERKENOBI", "Legacy Era"],
	["JEDIMASTERMACEWINDU", "Era of Revenge of the Sith"],
	["JOCASTANU", "Era of the Cavalry"],
	["JOLEEBINDO", "Legacy Era"],
	["JUHANI", "Legacy Era"],
	["JYNERSO", "Legacy Era"],
	["K2SO", "Legacy Era"],
	["KANANJARRUSS3", "Legacy Era"],
	["KELLERANBEQ", "Legacy Era"],
	["KIADIMUNDI", "Legacy Era"],
	["KITFISTO", "Legacy Era"],
	["KIX", "Era of Piracy"],
	["KLEYA", "Era of Andor"],
	["KRRSANTAN", "Legacy Era"],
	["KUIIL", "Legacy Era"],
	["KXSECURITYDROID", "Era of Andor"],
	["KYLEKATARN", "Legacy Era"],
	["KYLOREN", "Legacy Era"],
	["KYLORENUNMASKED", "Legacy Era"],
	["L3_37", "Legacy Era"],
	["LOBOT", "Legacy Era"],
	["LOGRAY", "Legacy Era"],
	["LORDVADER", "Legacy Era"],
	["LUKESKYWALKER", "Legacy Era"],
	["LUMINARAUNDULI", "Legacy Era"],
	["LUTHENRAEL", "Legacy Era"],
	["MACEWINDU", "Legacy Era"],
	["MAGMATROOPER", "Legacy Era"],
	["MAGNAGUARD", "Legacy Era"],
	["MAJORPARTAGAZ", "Era of Andor"],
	["MANDALORBOKATAN", "Legacy Era"],
	["MARAJADE", "Legacy Era"],
	["MARROK", "Legacy Era"],
	["MASTERQUIGON", "Legacy Era"],
	["MAUL", "Legacy Era"],
	["MAULHATEFUELED", "Era of Anniversary"],
	["MAULS7", "Legacy Era"],
	["MAZKANATA", "Era of Piracy"],
	["MERRIN", "Legacy Era"],
	["MISSIONVAO", "Legacy Era"],
	["MOFFGIDEONS1", "Legacy Era"],
	["MOFFGIDEONS3", "Legacy Era"],
	["MONMOTHMA", "Legacy Era"],
	["MORGANELSBETH", "Legacy Era"],
	["MOTHERTALZIN", "Legacy Era"],
	["NIGHTSISTERACOLYTE", "Legacy Era"],
	["NIGHTSISTERINITIATE", "Legacy Era"],
	["NIGHTSISTERSPIRIT", "Legacy Era"],
	["NIGHTSISTERZOMBIE", "Legacy Era"],
	["NIGHTTROOPER", "Legacy Era"],
	["NINTHSISTER", "Legacy Era"],
	["NUTEGUNRAY", "Legacy Era"],
	["OLDBENKENOBI", "Legacy Era"],
	["OMEGAS3", "Era of the Cavalry"],
	["OPERATIVE", "Era of Revenge of the Sith"],
	["PADAWANOBIWAN", "Legacy Era"],
	["PADAWANSABINE", "Era of Apprentices"],
	["PADMEAMIDALA", "Legacy Era"],
	["PAO", "Legacy Era"],
	["PAPLOO", "Legacy Era"],
	["PAZVIZSLA", "Legacy Era"],
	["PHASMA", "Legacy Era"],
	["PLOKOON", "Legacy Era"],
	["POE", "Legacy Era"],
	["POGGLETHELESSER", "Legacy Era"],
	["PRINCESSKNEESAA", "Legacy Era"],
	["PRINCESSLEIA", "Legacy Era"],
	["QIRA", "Legacy Era"],
	["QUEENAMIDALA", "Legacy Era"],
	["QUIGGOLD", "Era of Piracy"],
	["QUIGONJINN", "Legacy Era"],
	["R2D2_LEGENDARY", "Legacy Era"],
	["RANGETROOPER", "Legacy Era"],
	["RESISTANCEPILOT", "Legacy Era"],
	["RESISTANCETROOPER", "Legacy Era"],
	["REY", "Legacy Era"],
	["REYJEDITRAINING", "Legacy Era"],
	["ROSETICO", "Legacy Era"],
	["ROYALGUARD", "Legacy Era"],
	["SABINEWRENS3", "Legacy Era"],
	["SANASTARROS", "Legacy Era"],
	["SATELESHAN", "Era of Anniversary"],
	["SAVAGEOPRESS", "Legacy Era"],
	["SAWGERRERA", "Legacy Era"],
	["SCARIFREBEL", "Legacy Era"],
	["SCORCH", "Era of Revenge of the Sith"],
	["SCOUTTROOPER_V3", "Legacy Era"],
	["SECONDSISTER", "Legacy Era"],
	["SEVENTHSISTER", "Legacy Era"],
	["SHAAKTI", "Legacy Era"],
	["SHINHATI", "Legacy Era"],
	["SHORETROOPER", "Legacy Era"],
	["SITHASSASSIN", "Legacy Era"],
	["SITHMARAUDER", "Legacy Era"],
	["SITHPALPATINE", "Legacy Era"],
	["SITHTROOPER", "Legacy Era"],
	["SM33", "Era of Revenge of the Sith"],
	["SMUGGLERCHEWBACCA", "Legacy Era"],
	["SMUGGLERHAN", "Legacy Era"],
	["SNOWTROOPER", "Legacy Era"],
	["STAP", "Legacy Era"],
	["STARKILLER", "Legacy Era"],
	["STORMTROOPER", "Legacy Era"],
	["STORMTROOPERHAN", "Legacy Era"],
	["STORMTROOPERLUKE", "Era of Anniversary"],
	["STRANGER", "Era of Deadly Pursuits"],
	["SUNFAC", "Legacy Era"],
	["SUPREMELEADERKYLOREN", "Legacy Era"],
	["T3_M4", "Legacy Era"],
	["TALIA", "Legacy Era"],
	["TARFFUL", "Legacy Era"],
	["TARONMALICOS", "Legacy Era"],
	["TEEBO", "Legacy Era"],
	["THEMANDALORIAN", "Legacy Era"],
	["THEMANDALORIANBESKARARMOR", "Legacy Era"],
	["THIRDSISTER", "Legacy Era"],
	["TIEFIGHTERPILOT", "Legacy Era"],
	["TRENCH", "Legacy Era"],
	["TRIPLEZERO", "Legacy Era"],
	["TUSKENCHIEFTAIN", "Legacy Era"],
	["TUSKENHUNTRESS", "Legacy Era"],
	["TUSKENRAIDER", "Legacy Era"],
	["TUSKENSHAMAN", "Legacy Era"],
	["UGNAUGHT", "Legacy Era"],
	["UNDERCOVERLANDO", "Legacy Era"],
	["URORRURRR", "Legacy Era"],
	["VADER", "Legacy Era"],
	["VADERDUELSEND", "Era of Anniversary"],
	["VANE", "Era of Piracy"],
	["VANGUARDTEMPLEGUARD", "Era of Revenge of the Sith"],
	["VEERS", "Legacy Era"],
	["VEL", "Era of Andor"],
	["VISASMARR", "Legacy Era"],
	["WAMPA", "Legacy Era"],
	["WATTAMBOR", "Legacy Era"],
	["WEDGEANTILLES", "Legacy Era"],
	["WICKET", "Legacy Era"],
	["WRECKERS3", "Era of the Cavalry"],
	["YODACHEWBACCA", "Era of Anniversary"],
	["YOUNGCHEWBACCA", "Legacy Era"],
	["YOUNGHAN", "Legacy Era"],
	["YOUNGLANDO", "Legacy Era"],
	["ZAALBAR", "Legacy Era"],
	["ZAMWESELL", "Legacy Era"],
	["ZEBS3", "Legacy Era"],
	["ZORIIBLISS_V2", "Legacy Era"],
	["ZUCKUSS", "Era of Deadly Pursuits"],
]);

export { eras, type Era, eraByCharacter };
